name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: "^3.6.0"

dependencies:
  flutter:
    sdk: flutter
  ui:
    path: ../
  i18n:
    path: ../../../features/i18n
  artizan_ui:
    path: ../../../../artizan_ui

  widgetbook: ^3.10.2
  widgetbook_annotation: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  paipfood_package:
    path: ../../paipfood_package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.9.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
