name: core
description: Core package for PaipFood
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: "^3.6.0"

# Add regular dependencies here.
dependencies:
  dio: ^5.8.0+1
  logger: ^2.5.0
  uuid: ^4.5.1
  dart_jsonwebtoken: ^2.14.1
  talker: ^4.7.5
  talker_dio_logger: ^4.7.5
  path: ^1.8.3
  socket_io_client: ^3.1.2
  event_bus: ^2.0.1
  result_dart:
    git: https://github.com/eduardohr-muniz/result_dart
  sentry: ^9.1.0
  aes256: ^1.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.13
  mocktail: ^1.0.4
  analyzer: ^6.0.0
