name: paipfood_package
description: A new Flutter package project.
version: 0.0.1+2
publish_to: none
# homepage: paipfood_package

# resolution: workspace

environment:
  sdk: ">=3.7.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ui:
    path: ../ui
  flutter_svg: ^2.0.9
  hive: ^2.2.3

  mask_text_input_formatter: ^2.4.0
  toastification: ^2.3.0
  logger: ^2.5.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.0
  flutter_animate: ^4.2.0
  pin_code_fields: ^8.0.1
  universal_io: ^2.2.2
  collection: ^1.18.0
  uuid: ^4.2.1
  dotted_border: ^2.1.0
  cropperx: ^1.1.1
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  url_launcher: ^6.2.3
  sliver_tools: ^0.2.12
  package_info_plus: ^8.0.2
  lottie: ^3.1.0
  internet_connection_checker: ^1.0.0+1
  path: ^1.9.0
  image: ^4.1.7
  lucide_icons_flutter: ^3.0.0
  hugeicons: ^0.0.10
  dart_jsonwebtoken: ^2.14.2
  webview_flutter: ^4.10.0
  universal_html: ^2.2.4
  shared_preferences: ^2.3.4
  file_picker: ^8.1.7
  core:
    path: ../core
  core_flutter:
    path: ../core_flutter
  mocktail: ^1.0.4
  aws_client:
    ^0.7.0
    # path: ../../paipfood_back/db

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/flags/
    - assets/payments/
    - assets/lotties/
    - lib/l10n/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: icomoon
  #     fonts:
  #       - asset: lib/fonts/icomoon.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
