name: ui
description: "A new Flutter package project."
version: 0.0.1
homepage: none
publish_to: none

# resolution: workspace

environment:
  sdk: "^3.6.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  paipfood_package:
    path: ../paipfood_package
  talker_flutter: ^4.9.1
  # export
  flutter_breakpoints: ^1.0.0
  core:
    path: ../core
  core_flutter:
    path: ../core_flutter

  # export
  google_fonts: ^6.2.1
  universal_image: ^1.0.7
  lucide_icons_flutter: ^3.0.0
  flutter_animate: ^4.5.2
  two_dimensional_scrollables: ^0.3.3
  awesome_flutter_extensions: ^1.2.0
  collection: ^1.18.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  sentry_flutter: ^9.1.0
  artizan_ui:
    path: ../../../artizan_ui
  iconify_flutter: ^0.0.7
  lottie: ^3.3.1
  #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/lotties/
  fonts:
    - family: Geist
      fonts:
        - asset: fonts/Geist-Thin.otf
          weight: 100
        - asset: fonts/Geist-UltraLight.otf
          weight: 200
        - asset: fonts/Geist-Light.otf
          weight: 300
        - asset: fonts/Geist-Regular.otf
          weight: 400
        - asset: fonts/Geist-Medium.otf
          weight: 500
        - asset: fonts/Geist-SemiBold.otf
          weight: 600
        - asset: fonts/Geist-Bold.otf
          weight: 700
        - asset: fonts/Geist-Black.otf
          weight: 800
        - asset: fonts/Geist-UltraBlack.otf
          weight: 900
    - family: GeistMono
      fonts:
        - asset: fonts/GeistMono-Thin.otf
          weight: 100
        - asset: fonts/GeistMono-UltraLight.otf
          weight: 200
        - asset: fonts/GeistMono-Light.otf
          weight: 300
        - asset: fonts/GeistMono-Regular.otf
          weight: 400
        - asset: fonts/GeistMono-Medium.otf
          weight: 500
        - asset: fonts/GeistMono-SemiBold.otf
          weight: 600
        - asset: fonts/GeistMono-Bold.otf
          weight: 700
        - asset: fonts/GeistMono-Black.otf
          weight: 800
        - asset: fonts/GeistMono-UltraBlack.otf
          weight: 900
