name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  core:
    path: ../../packages/core
  auto_injector: ^2.0.5
  client_stripe: ^0.1.4
  dart_frog: ^1.2.0
  dart_frog_auth: ^1.1.0
  dart_frog_web_socket: ^1.0.0
  dart_jsonwebtoken: ^2.14.1
  dio: ^5.7.0
  logger: ^2.4.0
  shelf_cors_headers: ^0.1.5
  stripe_js: ^6.3.0
  uuid: ^4.5.1
  cron: ^0.6.1
  talker: ^4.7.1
  hipay: ^0.0.2
  hive_ce: ^2.11.2
  collection: ^1.19.0
  postgrest: ^2.4.2
  slang: ^4.8.1

dev_dependencies:
  mocktail: ^1.0.3
  hive_ce_generator: ^1.9.1
  build_runner: ^2.4.15
  test: ^1.25.5
  very_good_analysis: ^5.1.0
