export './obrigatory_validator.dart';
export './email_validator.dart';
export './password_validator.dart';
export './cpf_validator.dart';
export './cnpj_validator.dart';
export './cpf_cnpj_validator.dart';
export './phone_by_country_validator.dart';
export './cep_validator.dart';
export './postcode_validator.dart';
