name: app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  core: # ignore-slang
    path: ../../packages/core
  core_flutter:
    path: ../../packages/core_flutter
  ui:
    path: ../../packages/ui
  i18n:
    path: ../../features/i18n

  auth:
    path: ../../features/auth
  address:
    path: ../../features/address
  explore:
    path: ../../features/explore
  store:
    path: ../../features/store
  cart:
    path: ../../features/cart
  checkout:
    path: ../../features/checkout

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.7.0
  build_runner: ^2.5.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
